# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
package(
    default_visibility = ["//:__subpackages__"],
    licenses = ["notice"],
)

filegroup(
    name = "integration_test_data_files",
    testonly = 1,
    srcs = [
        "odws1_empty",
        "step1.txt",
        "step2.txt",
        "zip_test_folder.zip",
    ],
)

filegroup(
    name = "downloader_test_data_files",
    testonly = 1,
    srcs = [
        "full_file.txt",
        "partial_file.txt",
    ],
)
